### ISSUE TITLE
Add an explanation on how to use to the README

### ISSUE THREAD

**Issue by leonheess** [xgirma/latex-javaScript#9]
How would you integrate this into your document? Do I only need the .sty? How do import it? Where should I put it in my project?

**Comment by Sonophis** [comment]
Hey

### **Installing**

You need to put the **jslistings.sty** file in the same folder as your document.

If you want to show the code from a file, create a folder **/code** in the same folder as your document and put the file in it.

### **Using**

The examples provided in the **main.tex** file give you some hints as how the package needs to be used.

Write in the preamble of your document:

```
\usepackage{listings}
\usepackage{color}
\usepackage[pdftex]{xcolor}
\usepackage{textcomp}
\usepackage[T1]{fontenc}
\usepackage{caption}
\usepackage{hyperref}
\usepackage{jslistings}
```

When you need the formating to happen,

- from an external file (here **express.js** in the folder **/code**):
`\lstinputlisting[language=JavaScript, caption=Express.js]{code/express.js}`

- directly in the text:
```
\begin{lstlisting}

[...]
var http = require('http');
var path = require('path');
var methods = require('methods');
var express = require('express');

var isProduction = process.env.NODE_ENV === 'production';

// Create global app object
var app = express();

app.use(cors());
[...]

\end{lstlisting}
```

This is configured for **pdflatex**.

### **Lualatex**

If you are using lualatex, you will need to change some lines in the **jslistings.sty** file.

At the top of the file, change
```
\usepackage[pdftex]{xcolor}
\usepackage{textcomp}
\usepackage[T1]{fontenc}
```
to

`\usepackage[lualatex]{xcolor}`

(remove textcomp and fontenc)

Enjoy
